### ISSUE TITLE
dist directory not in the release :-(

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/invoke-filter#2]
@boennemann, could you help me here? If you see in my travis file, I run `npm run build`, this creates a `dist` directory that is referenced as my `main` in my `package.json`. When the build completes, semantic-release runs, but the resulting release is missing the `dist`. I think the problem is that I have the `dist` directory in the `.gitignore`. But I don't want to accidentally commit the `dist` directory into my repository. Should I just remove it from my `.gitignore` or is there any way to have a temporary directory that has everything I want released?

**Comment by boennemann** [comment]
The `dist` folder can remain in the `.gitignore` file, as long as you maintain an `.npmignore` file that lists all the things you want to exclude from the released package. A way to debug this is using `npm pack`. It creates a tarball with exactly the contents that would get published to registry. Hope that helps :) Let me know if you need something.

**Comment by kentcdodds** [comment]
Thanks @boennemann. It looks like npm has the `dist` folder, but the git release doesn't. In that case, I imagine that I need to actually remove the `dist` from the `.gitignore` right?

**Comment by boennemann** [comment]
What do you mean by "git release". Do you want to attach the tarball to the GitHub release? Or just push the dist files to another branch? Or push it back to you development branch?

**Comment by kentcdodds** [comment]
Sorry, yes, I meant I want it as part of the tarball to the GitHub release. Also, is there any way to run my build with the release version? For angular-formly at least, I output my distributable file with the release version (similar to what angular does with `angular.version`). I realize that's sort of a separate question...
